export const DEFAULT_SETTINGS = {
  players: {
    A: { name: "プレイヤーA" },
    B: { name: "プレイヤーB" },
  },
  firstPlayer: "A",
  gameTime: 5,
  cards: {
    c2: {
      enabled: true,
      conditionType: "exact",
      value: 2,
      min: null,
      max: null,
    },
    c3: {
      enabled: true,
      conditionType: "exact",
      value: 3,
      min: null,
      max: null,
    },
    c4: {
      enabled: true,
      conditionType: "exact",
      value: 4,
      min: null,
      max: null,
    },
    c5: {
      enabled: true,
      conditionType: "exact",
      value: 5,
      min: null,
      max: null,
    },
    c6: {
      enabled: true,
      conditionType: "exact",
      value: 6,
      min: null,
      max: null,
    },
    c7: {
      enabled: true,
      conditionType: "exact",
      value: 7,
      min: null,
      max: null,
    },
    c8: {
      enabled: true,
      conditionType: "exact",
      value: 8,
      min: null,
      max: null,
    },
    c9: {
      enabled: true,
      conditionType: "exact",
      value: 9,
      min: null,
      max: null,
    },
    c10: {
      enabled: true,
      conditionType: "exact",
      value: 10,
      min: null,
      max: null,
    },
    cJ: {
      enabled: true,
      conditionType: "min",
      value: 11,
      min: null,
      max: null,
    },
    cQ: {
      enabled: false,
      conditionType: "min",
      value: 12,
      min: null,
      max: null,
    },
    cK: {
      enabled: false,
      conditionType: "min",
      value: 13,
      min: null,
      max: null,
    },
  },
};

export const INITIAL_GAME_STATE = {
  gameStatus: "countdown",
  currentPlayer: "A",
  currentCard: null,
  timers: { A: 300, B: 300 },
  currentWord: "",
  history: [],
  endReason: null,
};
